### PR TITLE
Adds rosinstall for rocon_environment

### PR DESCRIPTION
**Pull request by FlyingPumba**
cc: @adamantivm 
Also, I created two folders in the workspace, to separate rocon_web_proxy from rocon_environment. Once merged, I'll update the Development Environment doc part of the rocon_web_proxy accordingly.

### CODE REVIEW

**Comment by adamantivm** [comment]
Is there any reason not to do everything in a single worskpace, instead of keeping two of them?

**Comment by FlyingPumba** [comment]
I didn't know if putting them all together will cause troubles or not. If you think it'll be better having it all in one .rosinstall file I can change it.

**Comment by adamantivm** [comment]
I would try with a single workspace, to simplify development.
Note that the other worskpace already has rosbridge_suite (from a fork)

**Comment by FlyingPumba** [comment]
ok, I'll modify it to be one single workspace

**Comment by FlyingPumba** [comment]
@adamantivm  ready. Random change in the proxy_server.sh, but I think is harmless.

**Pull request merged**
